"""delivery_engine.report - the deterministic visual report.

Step 21. The engine's generated eda_notebook.ipynb is the source of
truth: hashed findings, injected numbers. This module reads those same
findings and renders a professional, self-contained HTML report whose
charts are drawn ONLY from numbers already in the store.

THE GOVERNING PRINCIPLE: charts are cognitive scaffolding, not
conclusions. A chart provokes the right question and points the reader
at the evidence; it never answers for them, and it never computes. This
is the injected-numbers rule made visual - the report DRAWS hashed
findings, it does not calculate, estimate, or decide.

Determinism contract: the report is a pure function of the findings.
Every chart is inline SVG generated by fixed code from the findings
values - no randomness, no timestamps in the rendered region, no
network, no AI at runtime. The same findings produce byte-identical
HTML, so a reviewer can re-perform the report exactly and verify every
drawn number against the store.

Adaptivity WITHOUT judgement: which charts appear is decided by a fixed
rulebook keyed off the deterministic column profile the engine already
produced - more columns make a taller profile chart, and so on. The
data shapes the report through the hashed profile, never through an LLM
reading the data.

v1 draws only the three families whose numbers already exist in the
store: the DAMA scorecard, the validation results, and the per-column
profile shape. Richer target-based charts (class balance, rate by
segment) are a declared future extension that first requires a
deterministic stage to compute-and-hash those numbers - drawing them
today would require calculation, which the constitution forbids.
"""

from __future__ import annotations

import html
import json
from pathlib import Path
from typing import Any, Final

__all__ = ["ReportError", "build_report_html", "report_from_package"]

# Fixed professional palette (disclosed constants, never chosen at
# runtime). Colour never carries meaning alone - every chart pairs
# colour with a text label or value, per WCAG 1.4.1.
_INK: Final = "#1a2b4a"
_MUTED: Final = "#5b6b82"
_GOOD: Final = "#2e7d5b"
_WARN: Final = "#b45309"
_BAR_BG: Final = "#e8edf3"
_GRID: Final = "#d4dce6"
_ACCENT: Final = "#2b5c8a"

_CHART_W: Final = 640
_ROW_H: Final = 30
_BAR_H: Final = 18


class ReportError(Exception):
    """A report could not be built, stated cleanly with the reason."""


def _esc(text: object) -> str:
    """HTML-escape any value for safe embedding."""
    return html.escape(str(text), quote=True)


def _pct(value: float) -> str:
    """Deterministic percent label, 1 decimal - matches the notebook."""
    return f"{value * 100:.1f}%"


# ── charts: pure functions, findings values -> inline SVG ────────────────────


def _bar_row(y: int, label: str, value_label: str, frac: float, colour: str) -> str:
    """One horizontal bar with its label and value, as SVG.

    frac is a display width in [0, 1]; it is taken directly from a
    findings value, never computed here beyond scaling to pixels.
    """
    frac = max(0.0, min(1.0, frac))
    bar_w = round(frac * (_CHART_W - 220))
    text_y = y + _BAR_H - 4
    return (
        f'<text x="0" y="{text_y}" class="lbl">{_esc(label)}</text>'
        f'<rect x="150" y="{y}" width="{_CHART_W - 220}" '
        f'height="{_BAR_H}" fill="{_BAR_BG}" rx="3"/>'
        f'<rect x="150" y="{y}" width="{bar_w}" height="{_BAR_H}" '
        f'fill="{colour}" rx="3"/>'
        f'<text x="{_CHART_W - 60}" y="{text_y}" class="val">'
        f"{_esc(value_label)}</text>"
    )


def _svg(height: int, rows: str, title: str) -> str:
    """Wrap chart rows in an accessible SVG (role img + title/desc)."""
    return (
        f'<svg viewBox="0 0 {_CHART_W} {height}" '
        f'xmlns="http://www.w3.org/2000/svg" role="img" '
        f'aria-label="{_esc(title)}" class="chart">'
        f"<title>{_esc(title)}</title>{rows}</svg>"
    )


def _dama_chart(dama: dict[str, float | None]) -> str:
    """DAMA scorecard as bars. None ('not scored') is shown distinctly
    - never drawn as zero, because absence of a score is not a score of
    zero (the accuracy/timeliness honesty the engine insists on)."""
    rows = ""
    y = 8
    for dim in sorted(dama):
        val = dama[dim]
        if val is None:
            rows += (
                f'<text x="0" y="{y + _BAR_H - 4}" class="lbl">'
                f"{_esc(dim)}</text>"
                f'<rect x="150" y="{y}" width="{_CHART_W - 220}" '
                f'height="{_BAR_H}" fill="none" stroke="{_GRID}" '
                f'stroke-dasharray="4 3" rx="3"/>'
                f'<text x="{_CHART_W - 90}" y="{y + _BAR_H - 4}" '
                f'class="val muted">not scored</text>'
            )
        else:
            colour = _GOOD if val >= 0.999 else _WARN
            rows += _bar_row(y, dim, _pct(val), val, colour)
        y += _ROW_H
    return _svg(y + 4, rows, "Data quality scorecard, DAMA dimensions")


def _validation_chart(validate: dict[str, Any]) -> str:
    """Rules vs exceptions. The all-pass case renders as a clean row of
    zero-exception bars - a calm 'nothing to see', which is itself the
    finding."""
    results = validate["results"]
    total_exc = validate["total_exceptions"]
    max_fail = max((int(r["failures"]) for r in results), default=0)
    rows = ""
    y = 8
    for r in results:
        fails = int(r["failures"])
        frac = 0.0 if max_fail == 0 else fails / max_fail
        colour = _GOOD if fails == 0 else _WARN
        label = f"{r['rule_id']} {r['column']}"
        vlabel = "0 exceptions" if fails == 0 else f"{fails:,} exceptions"
        rows += _bar_row(y, label, vlabel, frac if fails else 0.0, colour)
        y += _ROW_H
    caption = f"{validate['rules_evaluated']} rules evaluated, {total_exc:,} total exceptions"
    return (
        _svg(y + 4, rows, "Validation results, exceptions per rule")
        + f'<p class="caption">{_esc(caption)}</p>'
    )


def _math_numeric_chart(numeric: dict[str, Any], skipped: list[str]) -> str:
    """Numeric column means as bars scaled to the widest column, with a
    95% CI overlay rect. All values injected from math-stage findings."""
    cols = sorted(numeric)
    max_mean = max((float(numeric[c]["mean"]) for c in cols), default=1.0) or 1.0
    bar_area = _CHART_W - 220
    rows = ""
    y = 8
    for col in cols:
        s = numeric[col]
        mean_v = float(s["mean"])
        ci_lo = float(s["mean_ci_low"])
        ci_hi = float(s["mean_ci_high"])
        n = int(s["n"])
        frac = max(0.0, min(1.0, mean_v / max_mean))
        bar_w = round(frac * bar_area)
        ci_lo_w = round(max(0.0, min(1.0, ci_lo / max_mean)) * bar_area)
        ci_hi_w = round(min(1.0, max(0.0, ci_hi / max_mean)) * bar_area)
        ci_w = max(ci_hi_w - ci_lo_w, 2)
        label = col[:19] + "…" if len(col) > 20 else col
        val_label = f"{mean_v:.4g} (n={n:,})"
        text_y = y + _BAR_H - 4
        rows += (
            f'<text x="0" y="{text_y}" class="lbl">{_esc(label)}</text>'
            f'<rect x="150" y="{y}" width="{bar_area}" height="{_BAR_H}"'
            f' fill="{_BAR_BG}" rx="3"/>'
            f'<rect x="150" y="{y}" width="{bar_w}" height="{_BAR_H}"'
            f' fill="{_ACCENT}" rx="3"/>'
            f'<rect x="{150 + ci_lo_w}" y="{y + 4}" width="{ci_w}"'
            f' height="{_BAR_H - 8}" fill="{_INK}" opacity="0.30" rx="1"/>'
            f'<text x="{_CHART_W - 60}" y="{text_y}" class="val">'
            f"{_esc(val_label)}</text>"
        )
        y += _ROW_H
    for col in sorted(skipped):
        label = col[:19] + "…" if len(col) > 20 else col
        text_y = y + _BAR_H - 4
        rows += (
            f'<text x="0" y="{text_y}" class="lbl">{_esc(label)}</text>'
            f'<rect x="150" y="{y}" width="{bar_area}" height="{_BAR_H}"'
            f' fill="none" stroke="{_GRID}" stroke-dasharray="4 3" rx="3"/>'
            f'<text x="{_CHART_W - 90}" y="{text_y}"'
            f' class="val muted">omitted</text>'
        )
        y += _ROW_H
    if not cols and not skipped:
        return '<p class="note">No numeric columns in this dataset.</p>'
    return _svg(
        y + 4,
        rows,
        "Numeric column means with 95% confidence interval",
    )


def _math_categorical_chart(categorical: dict[str, Any], skipped: list[str]) -> str:
    """Categorical column Shannon entropy as bars. entropy_normalized is
    already in [0, 1] from the findings store - no scaling required."""
    cols = sorted(categorical)
    rows = ""
    y = 8
    for col in cols:
        s = categorical[col]
        frac = max(0.0, min(1.0, float(s["entropy_normalized"])))
        bits = float(s["entropy_bits"])
        distinct = int(s["distinct"])
        label = col[:19] + "…" if len(col) > 20 else col
        val_label = f"{bits:.3g} bits / {distinct:,} cat."
        rows += _bar_row(y, label, val_label, frac, _ACCENT)
        y += _ROW_H
    for col in sorted(skipped):
        label = col[:19] + "…" if len(col) > 20 else col
        text_y = y + _BAR_H - 4
        rows += (
            f'<text x="0" y="{text_y}" class="lbl">{_esc(label)}</text>'
            f'<rect x="150" y="{y}" width="{_CHART_W - 220}"'
            f' height="{_BAR_H}" fill="none" stroke="{_GRID}"'
            f' stroke-dasharray="4 3" rx="3"/>'
            f'<text x="{_CHART_W - 90}" y="{text_y}"'
            f' class="val muted">omitted</text>'
        )
        y += _ROW_H
    if not cols and not skipped:
        return '<p class="note">No categorical columns in this dataset.</p>'
    return _svg(
        y + 4,
        rows,
        "Categorical column Shannon entropy, normalized",
    )


def _math_section(math: dict[str, Any]) -> str:
    """Assemble the Descriptive statistics HTML from math-stage findings."""
    numeric: dict[str, Any] = math.get("numeric", {})
    categorical: dict[str, Any] = math.get("categorical", {})
    skipped: list[str] = math.get("skipped", [])
    parts: list[str] = []
    if numeric or skipped:
        parts.append(
            '<p class="note">Numeric columns — bar shows mean scaled'
            " to the column with the largest mean; dark band marks the"
            " 95% confidence interval from the findings store."
            " Dashed rows were omitted from analysis.</p>"
        )
        parts.append(_math_numeric_chart(numeric, skipped))
    if categorical or skipped:
        parts.append(
            '<p class="note">Categorical columns — normalized Shannon'
            " entropy (0 = one category dominates,"
            " 1 = fully uniform)."
            " Dashed rows were omitted from analysis.</p>"
        )
        parts.append(_math_categorical_chart(categorical, skipped))
    if not parts:
        parts.append('<p class="note">No math-stage findings in this package.</p>')
    return "".join(parts)


def _profile_chart(columns: list[dict[str, Any]]) -> str:
    """Per-column completeness (share of non-null rows). Height adapts
    to the number of columns - this is the 'adaptive through the hashed
    profile' property: the data shapes the chart, by code, not by an AI
    deciding anything."""
    rows = ""
    y = 8
    for col in columns:
        comp = float(col["completeness"])
        colour = _GOOD if comp >= 0.999 else _WARN
        label = str(col["name"])
        if len(label) > 20:
            label = label[:19] + "\u2026"
        rows += _bar_row(y, label, _pct(comp), comp, colour)
        y += _ROW_H
    return _svg(y + 4, rows, "Column completeness, share of non-null rows")


# ── page assembly ────────────────────────────────────────────────────────────


_CSS: Final = """
:root { color-scheme: light; }
* { box-sizing: border-box; }
body {
  font-family: "Segoe UI", -apple-system, BlinkMacSystemFont, Roboto,
    "Helvetica Neue", "Noto Sans", Ubuntu, Cantarell, Arial, sans-serif;
  color: #1a2b4a; background: #ffffff; margin: 0;
  line-height: 1.55; -webkit-font-smoothing: antialiased;
  text-rendering: optimizeLegibility;
  font-feature-settings: "kern" 1, "liga" 1;
}
h1, h2 {
  font-family: "Segoe UI Semibold", "Segoe UI", -apple-system,
    BlinkMacSystemFont, "Helvetica Neue", Arial, sans-serif;
}
.num, td.num, code {
  font-family: "SF Mono", "Segoe UI Mono", "Roboto Mono", Menlo,
    Consolas, "Liberation Mono", monospace;
}
.wrap { max-width: 820px; margin: 0 auto; padding: 56px 32px 80px; }
header { border-bottom: 2px solid #1a2b4a; padding-bottom: 20px;
  margin-bottom: 8px; }
h1 { font-size: 1.9rem; margin: 0 0 6px; letter-spacing: -0.01em; }
.sub { color: #5b6b82; font-size: 0.95rem; margin: 0; }
.lede { color: #33465f; font-size: 1.02rem; margin: 24px 0 8px; }
section { margin-top: 44px; }
h2 { font-size: 1.15rem; margin: 0 0 4px; color: #1a2b4a; }
.note { color: #5b6b82; font-size: 0.88rem; margin: 0 0 16px; }
.chart { width: 100%; height: auto; display: block; margin: 8px 0; }
.chart .lbl { font: 500 13px sans-serif; fill: #33465f; }
.chart .val { font: 600 13px sans-serif; fill: #1a2b4a;
  text-anchor: end; }
.chart .val.muted { fill: #8794a6; font-weight: 500; }
.caption { color: #5b6b82; font-size: 0.9rem; margin: 4px 0 0; }
table { border-collapse: collapse; width: 100%; margin: 8px 0;
  font-size: 0.92rem; }
th, td { text-align: left; padding: 7px 10px;
  border-bottom: 1px solid #e8edf3; }
th { color: #5b6b82; font-weight: 600; }
td.num { text-align: right; font-variant-numeric: tabular-nums; }
footer { margin-top: 64px; padding-top: 20px;
  border-top: 1px solid #e8edf3; color: #5b6b82; font-size: 0.82rem; }
footer code { font-size: 0.78rem; word-break: break-all;
  color: #33465f; }
.sig { margin-top: 8px; color: #33465f; }
"""


def _profile_table(columns: list[dict[str, Any]]) -> str:
    """The column profile as a proper table - the exact hashed values,
    scannable. Complements the completeness chart above it."""
    body = ""
    for c in columns:
        body += (
            "<tr>"
            f"<td>{_esc(c['name'])}</td>"
            f"<td>{_esc(c['dtype'])}</td>"
            f"<td class='num'>{int(c['total']):,}</td>"
            f"<td class='num'>{int(c['nulls']):,}</td>"
            f"<td class='num'>{int(c['distinct']):,}</td>"
            f"<td class='num'>{_pct(float(c['valid_ratio']))}</td>"
            "</tr>"
        )
    return (
        "<table><thead><tr>"
        "<th>Column</th><th>Type</th><th>Rows</th><th>Nulls</th>"
        "<th>Distinct</th><th>Validity</th>"
        "</tr></thead><tbody>" + body + "</tbody></table>"
    )


def build_report_html(
    profile: dict[str, Any],
    validate: dict[str, Any],
    source: str,
    profile_digest: str,
    validate_digest: str,
    generated_date: str = "",
    math: dict[str, Any] | None = None,
    math_digest: str = "",
) -> str:
    """Render the full self-contained HTML report from findings.

    A pure function: the same arguments always produce byte-identical
    output. Every number shown is taken directly from `profile`,
    `validate`, or `math`; nothing is computed here beyond scaling
    values to pixel widths and formatting them for display.

    `generated_date` is optional display metadata for the footer. It is
    the ONLY value that varies between runs, and it lives outside the
    findings region: the report's content stays a deterministic
    function of the findings, while the date honestly records when the
    file was rendered. Pass a fixed string for byte-stable output.

    `math` is the findings dict from math.json; when None the
    Descriptive statistics section is omitted entirely.
    """
    dama = profile["dama_scores"]
    columns = profile["columns"]

    doc = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Data review - {_esc(source)}</title>
<style>{_CSS}</style>
</head>
<body>
<main class="wrap">
<header>
<h1>Data review</h1>
<p class="sub">Source: {_esc(source)}</p>
</header>

<p class="lede">Every figure below was computed by the deterministic
engine and drawn directly from the hashed findings store. These charts
are a starting point for your own review - they show the shape of the
data so you can decide where to look, not what to conclude.</p>

<section>
<h2>Data quality scorecard</h2>
<p class="note">DAMA six dimensions. Accuracy and timeliness are shown
as "not scored" where the dataset alone cannot establish them - absence
of a score is never drawn as a score of zero.</p>
{_dama_chart(dama)}
</section>

<section>
<h2>Validation results</h2>
<p class="note">Exceptions per rule. Exceptions are reported, never
dropped - every failure is evidence.</p>
{_validation_chart(validate)}
</section>

<section>
<h2>Column completeness</h2>
<p class="note">Share of non-null rows per column. The chart height
follows the data - it adapts to however many columns the profile
found.</p>
{_profile_chart(columns)}
</section>

<section>
<h2>Column profile</h2>
<p class="note">The exact profiled values behind the chart above.</p>
{_profile_table(columns)}
</section>

{
        f'''<section>
<h2>Descriptive statistics</h2>
<p class="note">Distribution summary from the math-stage findings.
Every value traces to math.json in the findings store.</p>
{_math_section(math)}
</section>'''
        if math is not None
        else ""
    }

<footer>
{f"<p>Report generated: {_esc(generated_date)}</p>" if generated_date else ""}
<p>Provenance and verification. Recompute the SHA-256 of each findings
file and compare against these digests; every number in this report
traces to them.</p>
<p>dq_profile: <code>{_esc(profile_digest)}</code></p>
<p>dq_validate: <code>{_esc(validate_digest)}</code></p>
{f"<p>math: <code>{_esc(math_digest)}</code></p>" if math_digest else ""}
<p class="sig">Rendered deterministically by the Delivery Engine from
the hashed findings store. No figure was computed, estimated, or
authored by an AI - the report draws the evidence, the reader supplies
the judgement.</p>
</footer>
</main>
</body>
</html>
"""
    return doc


def report_from_package(package_dir: str) -> Path:
    """Read a sealed package's findings and write report.html into it.

    Works from the committed JSON files, so it runs on any package
    directory without a live store. Returns the path written.
    """
    pkg = Path(package_dir)
    if not pkg.is_dir():
        raise ReportError(f"Not a directory: {package_dir}")
    findings = pkg / "findings"
    prof_path = findings / "dq_profile.json"
    val_path = findings / "dq_validate.json"
    for p in (prof_path, val_path):
        if not p.exists():
            raise ReportError(
                f"Expected findings file not found: {p}. The report is "
                f"built from a sealed package's dq_profile and "
                f"dq_validate findings."
            )
    prof_doc = json.loads(prof_path.read_text(encoding="utf-8"))
    val_doc = json.loads(val_path.read_text(encoding="utf-8"))

    # Findings files store the payload under "findings" with the digest
    # alongside; fall back gracefully if given a bare findings dict.
    profile = prof_doc.get("findings", prof_doc)
    validate = val_doc.get("findings", val_doc)
    prof_digest = str(prof_doc.get("sha256", ""))
    val_digest = str(val_doc.get("sha256", ""))

    # Recover the source label if the manifest records it; else neutral.
    source = "the analysed dataset"
    manifest = pkg / "manifest.json"
    if manifest.exists():
        m = json.loads(manifest.read_text(encoding="utf-8"))
        fp = m.get("source_fingerprint", {})
        if isinstance(fp, dict) and fp.get("path"):
            source = str(fp["path"])

    # Load optional math.json — present when the math stage has run.
    math_path = findings / "math.json"
    math_findings: dict[str, Any] | None = None
    math_digest = ""
    if math_path.exists():
        math_doc = json.loads(math_path.read_text(encoding="utf-8"))
        math_findings = math_doc.get("findings", math_doc)
        math_digest = str(math_doc.get("sha256", ""))

    # The generation date is display metadata, injected here (not in
    # the pure builder) so build_report_html stays byte-deterministic.
    from datetime import date

    generated = date.today().strftime("%d %B %Y")
    doc_html = build_report_html(
        profile,
        validate,
        source,
        prof_digest,
        val_digest,
        generated,
        math=math_findings,
        math_digest=math_digest,
    )
    out = pkg / "report.html"
    out.write_text(doc_html, encoding="utf-8")
    return out
